# Generated by Django 5.0.6 on 2025-05-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinteraction',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
    ]
